 Implement a python program that performs basic arithmetic operations using TensorFlow.

In [ ]:
import tensorflow as tf

# Define two constant tensors
a = tf.constant(10)
b = tf.constant(5)

# Perform arithmetic operations
add_result = tf.add(a, b)
sub_result = tf.subtract(a, b)
mul_result = tf.multiply(a, b)
div_result = tf.divide(a, b)

# Print results
print("Tensor a:", a.numpy())
print("Tensor b:", b.numpy())
print("Addition (a + b):", add_result.numpy())
print("Subtraction (a - b):", sub_result.numpy())
print("Multiplication (a * b):", mul_result.numpy())
print("Division (a / b):", div_result.numpy())


Tensor a: 10
Tensor b: 5
Addition (a + b): 15
Subtraction (a - b): 5
Multiplication (a * b): 50
Division (a / b): 2.0


 Implement a python program that performs matrix operations using TensorFlow.

In [ ]:
import tensorflow as tf

# Define two 2x2 matrices
A = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

B = tf.constant([[5.0, 6.0],
                 [7.0, 8.0]])

# Matrix addition
add_result = tf.add(A, B)

# Matrix subtraction
sub_result = tf.subtract(A, B)

# Matrix multiplication (dot product)
matmul_result = tf.matmul(A, B)

# Transpose of A
transpose_A = tf.transpose(A)

# Determinant of A
det_A = tf.linalg.det(A)

# Inverse of A (only if determinant ≠ 0)
inverse_A = tf.linalg.inv(A)

# Print results
print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())
print("Addition (A + B):\n", add_result.numpy())
print("Subtraction (A - B):\n", sub_result.numpy())
print("Multiplication (A * B):\n", matmul_result.numpy())
print("Transpose of A:\n", transpose_A.numpy())
print("Determinant of A:", det_A.numpy())
print("Inverse of A:\n", inverse_A.numpy())


Matrix A:
 [[1. 2.]
 [3. 4.]]
Matrix B:
 [[5. 6.]
 [7. 8.]]
Addition (A + B):
 [[ 6.  8.]
 [10. 12.]]
Subtraction (A - B):
 [[-4. -4.]
 [-4. -4.]]
Multiplication (A * B):
 [[19. 22.]
 [43. 50.]]
Transpose of A:
 [[1. 3.]
 [2. 4.]]
Determinant of A: -2.0
Inverse of A:
 [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


Write python to find the number of zeros at the end of a factorial of a given positive number using tensorflow.

In [3]:
import tensorflow as tf

@tf.function
def trailing_zeros_in_factorial(n):
    count = tf.constant(0, dtype=tf.int32)
    i = tf.constant(5, dtype=tf.int32)

    # Loop while n // i > 0
    while tf.math.greater(n // i, 0):
        count += n // i
        i *= 5

    return count

# Example usage
n = tf.constant(75, dtype=tf.int32)
result = trailing_zeros_in_factorial(n)
tf.print("Number of trailing zeros in", n, "factorial is:", result)


Number of trailing zeros in 75 factorial is: 18


Using tensorflow Write a Python function to check whether a number is perfect or not.
 The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1
 + 2 + 3 = 6. Equivalently, the number 6 is equal to half the sum of all its positive
 divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6. The next perfect number is 28 = 1 + 2 + 4 + 7 + 14.
 This is followed by the perfect numbers 496 and 8128.

In [4]:
import tensorflow as tf

@tf.function
def is_perfect_number(n):
    total = tf.constant(0, dtype=tf.int32)

    # Loop from 1 to n//2 to find proper divisors
    for i in tf.range(1, n // 2 + 1):
        if n % i == 0:
            total += i

    # Return True if the sum of divisors equals n
    return tf.equal(total, n)

# Test the function
test_numbers = [6, 28, 496, 8128, 10, 12, 97]

for num in test_numbers:
    result = is_perfect_number(tf.constant(num))
    tf.print("Is", num, "a perfect number?", result)


Is 6 a perfect number? 1
Is 28 a perfect number? 1
Is 496 a perfect number? 1
Is 8128 a perfect number? 1
Is 10 a perfect number? 0
Is 12 a perfect number? 0
Is 97 a perfect number? 0


Using tensorflow Write a python program to check the validity of password without using any built-in
 functions or modules. Password checker program basically checks if a password is
 valid or not based on the password policies mention below:
 • Password should contain at least one lowercase letter(a-z).
 • Password should contain at least one uppercase letter(A-Z).
 • Password should contain at least one special character (@, #, %, &amp;, !, $, etc…).
 • Password should not contain any space.
 • Password should contain at least one digit (0-9).
 • Password length should be between 8 to 15 characters.
 • It should not contain the repeated combination of consecutive 3 characters.
 Also check whether the password is strong or not without using any built-in function.
 Given a string, find its strength. Let a strong password is one that satisfies all above
 conditions. A moderate password is one that satisfies first three conditions and has
 length at least 6. Otherwise password is weak.

In [ ]:
import tensorflow as tf

def check_password_easy(password):
    chars = tf.constant([ord(c) for c in password], dtype=tf.int32)
    length = tf.shape(chars)[0]

    has_lower = has_upper = has_digit = has_special = has_space = False

    specials = [33, 35, 36, 37, 38, 64]  # ! # $ % & @

    for c in chars.numpy():
        if 97 <= c <= 122:  # a-z
            has_lower = True
        elif 65 <= c <= 90:  # A-Z
            has_upper = True
        elif 48 <= c <= 57:  # 0-9
            has_digit = True
        elif c in specials:
            has_special = True
        elif c == 32:  # space
            has_space = True

    # Rule: no repeated 3-character combination
    no_repeat = True
    s = password
    for i in range(len(s) - 5):
        if s[i:i+3] == s[i+3:i+6]:
            no_repeat = False
            break

    # All conditions
    valid = (8 <= len(password) <= 15 and
             has_lower and has_upper and has_digit and
             has_special and not has_space and no_repeat)

    # Strength evaluation
    if valid:
        strength = "Strong"
    elif has_lower and has_upper and has_special and len(password) >= 6:
        strength = "Moderate"
    else:
        strength = "Weak"

    return valid, strength

# ✅ Test Examples
passwords = ["Pass@123", "weak1", "NoSpecial123", "Perfect@123!", "aaaAAA111!!!", "abcABC123abcABC123"]

for pwd in passwords:
    valid, strength = check_password_easy(pwd)
    print(f"Password: {pwd:20} | Valid: {valid} | Strength: {strength}")


Password: Pass@123             | Valid: True | Strength: Strong
Password: weak1                | Valid: False | Strength: Weak
Password: NoSpecial123         | Valid: False | Strength: Weak
Password: Perfect@123!         | Valid: True | Strength: Strong
Password: aaaAAA111!!!         | Valid: True | Strength: Strong
Password: abcABC123abcABC123   | Valid: False | Strength: Weak


Using tensorflow write a python code to Take that list and finds all pairs of integers that differ by three.

In [ ]:
import tensorflow as tf

def find_symmetric_pairs_diff_by_three(input_list):
    nums = tf.constant(input_list, dtype=tf.int32)
    pairs = []

    for i in range(len(input_list)):
        for j in range(len(input_list)):
            if i != j:
                diff = tf.abs(nums[i] - nums[j])
                if diff == 3:
                    pairs.append((nums[i].numpy(), nums[j].numpy()))

    return pairs

# 🔎 Test
input_list = [1, 4, 7, 10, 2, 5, 8]
pairs = find_symmetric_pairs_diff_by_three(input_list)

print("Fully symmetric pairs with difference of 3:")
for p in pairs:
    print(p)


Fully symmetric pairs with difference of 3:
(np.int32(1), np.int32(4))
(np.int32(4), np.int32(1))
(np.int32(4), np.int32(7))
(np.int32(7), np.int32(4))
(np.int32(7), np.int32(10))
(np.int32(10), np.int32(7))
(np.int32(2), np.int32(5))
(np.int32(5), np.int32(2))
(np.int32(5), np.int32(8))
(np.int32(8), np.int32(5))


In [5]:
ord('A')

65

In [6]:
ord('Z')

90

In [7]:
ord('a')

97

In [8]:
ord('z')

122

In [9]:
ord("@")

64

In [10]:
ord(" ")

32

In [12]:
chr(65)

'A'

In [13]:
chr(32)

' '

In [ ]:
chr(1)